// Server component. Defines SEO metadata + JSON-LD structured data for /vial.
// Page content lives in page.js (client component for animations + FAQ accordion).
// The OG/Twitter image is generated by the colocated opengraph-image.js (Next
// file convention), so no explicit image URL is set in metadata here.

import { JetBrains_Mono } from "next/font/google";

// Vial's number font. Exposed as --font-jetbrains and consumed by the inline
// `mono` styles in page.js. Matches the mobile app (constants/typography.js).
const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains",
  display: "swap",
});

const SITE = "https://echoforge.to";
const PAGE_URL = `${SITE}/vial`;

export const metadata = {
  metadataBase: new URL(SITE),
  title: "Vial: Peptide, GLP-1 & TRT Dose Tracker",
  description:
    "The peptide, GLP-1, and TRT tracker for iPhone. Log every dose, set on-device reminders, and track BPC-157, GLP-1s, TRT, and more. Free to start. AI coach included with Vial.",
  keywords: [
    "peptide tracker",
    "peptide dose tracker",
    "dose tracker",
    "GLP-1 tracker",
    "BPC-157",
    "TB-500",
    "CJC-1295",
    "ipamorelin",
    "GHK-Cu",
    "semaglutide",
    "tirzepatide",
    "ozempic tracker",
    "mounjaro tracker",
    "TRT tracker",
    "testosterone tracker",
    "HCG",
    "injection tracker",
    "peptide log",
    "dose reminder",
    "peptide AI",
  ],
  alternates: { canonical: PAGE_URL },
  openGraph: {
    type: "website",
    url: PAGE_URL,
    title: "Vial: Peptide, GLP-1 & TRT Dose Tracker",
    description:
      "The peptide, GLP-1, and TRT tracker for iPhone. Log every dose, set on-device reminders, and track BPC-157, GLP-1s, TRT, and more. Free to start.",
    siteName: "Vial",
  },
  twitter: {
    card: "summary_large_image",
    title: "Vial: Peptide, GLP-1 & TRT Dose Tracker",
    description:
      "Log every dose, set reminders, and track BPC-157, GLP-1s, TRT, and more. Free to start. AI coach included.",
  },
  robots: { index: true, follow: true },
};

// JSON-LD structured data. Content is fully controlled by this file (no user
// input flows through), so dangerouslySetInnerHTML is safe here. This is the
// pattern documented by Next.js for structured data:
// https://nextjs.org/docs/app/building-your-application/optimizing/metadata#json-ld
export default function VialLayout({ children }) {
  const softwareJsonLd = {
    "@context": "https://schema.org",
    "@type": "MobileApplication",
    name: "Vial: Peptide Tracker",
    operatingSystem: "iOS",
    applicationCategory: "HealthApplication",
    description:
      "The peptide, GLP-1, and TRT tracker for iPhone. Log every dose, set on-device reminders, and track BPC-157, GLP-1s, TRT, and more. Free to start. AI coach included with Vial.",
    url: PAGE_URL,
    publisher: { "@type": "Organization", name: "EchoForge", url: SITE },
    offers: [
      { "@type": "Offer", name: "Vial Monthly", price: "14.99", priceCurrency: "USD", category: "subscription" },
      { "@type": "Offer", name: "Vial Yearly", price: "49.99", priceCurrency: "USD", category: "subscription", description: "$29.99 first year intro for new subscribers, then $49.99/year" },
      { "@type": "Offer", name: "Vial Lifetime", price: "99.99", priceCurrency: "USD", category: "lifetime" },
    ],
    featureList: [
      "Vial inventory with expiry and fridge-life alerts",
      "Dose tracker with three-state logging",
      "Smart injection site rotation",
      "Cycle scheduling for on/off protocols",
      "Body metrics and bloodwork tracking",
      "Progress photos",
      "Vial 365 year-end share asset",
      "Vial AI educational coach",
      "On-device, no account required",
    ],
  };

  const orgJsonLd = {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: "EchoForge",
    url: SITE,
    sameAs: [],
    contactPoint: [{ "@type": "ContactPoint", email: "support@echoforge.to", contactType: "customer support" }],
  };

  // FAQPage schema is NOT emitted here. It lives on the pages that actually
  // render the questions (landing page.js, /vial/faq, /vial/support) so the
  // structured data matches the visible content on each page.
  const ldHtml = [softwareJsonLd, orgJsonLd]
    .map((d) => `<script type="application/ld+json">${JSON.stringify(d).replace(/</g, "\\u003c")}</script>`)
    .join("");

  // The whole /vial path is forced to Vial's light brand palette, independent
  // of the EchoForge studio theme toggle. Overriding the CSS theme vars here
  // means the legal subpages (which use text-foreground / text-accent tokens)
  // render light and Vial-accented without per-page edits. The landing page
  // sets its own inline hexes and is unaffected.
  const vialTheme = {
    "--background": "#F4F4F5",
    "--foreground": "#09090B",
    "--muted": "#52525B",
    "--border": "#D4D4D8",
    "--secondary": "#E8E8EA",
    "--accent": "#00B380",
    backgroundColor: "#F4F4F5",
    color: "#09090B",
    minHeight: "100vh",
  };

  return (
    <div className={jetbrains.variable} style={vialTheme}>
      <div dangerouslySetInnerHTML={{ __html: ldHtml }} />
      {children}
    </div>
  );
}
